content/electronics/arduino_setup.rst
content/labs/blinky_1.rst
content/labs/blinky_2.rst
content/labs/flex_data_acquisition.rst
content/labs/index.rst
content/labs/part_manufacture.rst
content/labs/project_proposal.rst
content/lectures/index.rst
content/lectures/lecture_1_2.rst
content/lectures/lecture_3.rst
content/lectures/lecture_4.rst
content/lectures/lecture_5.rst
content/lectures/lecture_6.rst
content/lectures/lecture_7.rst
index.rst

Add the initial content for weeks 1-3 of class, some activities are stubs.

Week 1 to 3 content add

---

content/labs/project_proposal.rst

Complete draft of project proposal activity.

Make project proposal goals a bullet list and update title

---

conf.py
content/lectures/course_ad.rst
content/lectures/index.rst
content/lectures/syllabus.rst

Add the course syllabus and an Ad for the class.

Syllabus and Ad

---

content/shop/index.rst
content/shop/measurement_tools/calipers.rst
content/shop/measurement_tools/gauges.rst
content/shop/measurement_tools/index.rst
content/shop/measurement_tools/indicators.rst
content/shop/measurement_tools/micrometers.rst
content/shop/measurement_tools/reading_vernier.rst
content/shop/measurement_tools/tapes_and_rules.rst

Adds a section on measurement tools. Could use more pictures and videos if there is time/interest. Addresses #20

Add Measurement Tools

---

content/lectures/index.rst
content/lectures/lecture_10.rst
content/lectures/lecture_11.rst
content/lectures/lecture_12.rst
content/lectures/lecture_13.rst
content/lectures/lecture_14.rst
content/lectures/lecture_15.rst
content/lectures/lecture_16.rst
content/lectures/lecture_17.rst
content/lectures/lecture_18.rst
content/lectures/lecture_19.rst
content/lectures/lecture_20.rst
content/lectures/lecture_21.rst
content/lectures/lecture_22.rst
content/lectures/lecture_23.rst
content/lectures/lecture_24_25.rst
content/lectures/lecture_26.rst
content/lectures/lecture_27.rst
content/lectures/lecture_28.rst
content/lectures/lecture_29.rst
content/lectures/lecture_30.rst
content/lectures/lecture_31_32.rst
content/lectures/lecture_8.rst
content/lectures/lecture_9.rst

Add skeleton outlines for all lectures for the semester.

Add class outlines

---

content/electronics/arduino_setup.rst
content/labs/project_brainstorm.rst
content/shop/hand_tools/files.rst
content/shop/hand_tools/wrenches.rst
content/shop/machine_tools/index.rst
content/shop/machine_tools/plasma_cutter.rst

Typo fixes

---

content/lectures/lecture_8.rst

Fix link to Arduino stoplight activity

---

content/shop/machine_tools/EDM.rst

Add basic EDM safety information to address #47

Add EDM safety precautions

---

content/syllabus.rst

Change course description to match that of the ad.

Update syllabus text

---

content/shop/machine_tools/EDM.rst

Moved EDM safety precautions to end for consistency.
Line edit to make hazard plural.

Minor edits

---

content/labs/digital_representation.rst
content/labs/index.rst

Adapted the initial LaTeX version of the exercise. Addresses #43

Add digital representation activity

---

content/labs/project_brainstorm.rst
content/lectures/lecture_3.rst

Add link to lecture 3 activity and clarify the brainstorming assignment

Lecture 3 pre class update

---

content/labs/blinky_1.rst
content/lectures/lecture_3.rst

Add slides and video from lecture 3. Also add FTDI driver link to Arduino activity to fix issue some people had.

Lecture 3 update

---

content/lectures/lecture_4.rst

Add slides - video did not record properly.

Add lecture 4 slides

---

content/lectures/lecture_6.rst

Update lecture 6 to be ready for class.

Lecture 6 preparation

---

content/lectures/lecture_4.rst

Add video screencast of lecture

Update lecture 4

---

content/labs/3D_print_activity.rst
content/labs/arduino_stoplight.rst
content/labs/blinky_1.rst
content/labs/blinky_2.rst
content/labs/digital_representation.rst
content/labs/flex_data_acquisition.rst
content/labs/part_manufacture.rst
content/labs/project_brainstorm.rst
content/labs/project_proposal.rst
content/labs/state_machine_XRD.rst
content/labs/threading_activity.rst

Add grading rubrics so students know how each assignment will be graded.

Add grading rubrics

---

content/lectures/lecture_5.rst
content/lectures/lecture_6.rst

Add lecture 6 slides and video.

Lecture 6 update

---

content/lectures/lecture_7.rst

Add lecture 7 content

---

content/lectures/lecture_8.rst

Add slides for lecture - video will come later as a screencast.

Add lecture 8 slides

---

content/labs/arduino_stoplight.rst

Change resistor color codes

---

content/lectures/lecture_7.rst

Add link to YouTube video of lecture

Add lecture 7 video

---

content/labs/digital_representation.rst

Add necessary spaces for table formatting.

Fix table in assignment

---

content/lectures/lecture_10.rst

Add slides and links for lecture 10

Add lecture 10 slides

---

content/labs/digital_representation.rst

Make questions more specific to help eliminate some confusion.

Fix typo and clarify per student feedback

---

content/labs/digital_representation.rst

After grading there were a few things that were unclear, so I have attempted to clarify and make the assignment better for the next go around.

Clarify after students have completed assignment

---

content/lectures/lecture_11.rst
content/lectures/lecture_12.rst
content/lectures/lecture_13.rst

Add slides for lectures 11, 12, 13

Add slides for lectures

---

content/labs/3D_print_activity.rst

Addresses #88 about a broken maker commons link.

Fix maker commons link

---

content/lectures/lecture_11.rst
content/lectures/lecture_12.rst
content/lectures/lecture_13.rst
content/lectures/lecture_14.rst

Add lecture videos and activity links.

Update with lecture materials

---

content/resources/electronics_suppliers.rst
content/resources/index.rst
content/resources/mechanical_suppliers.rst
content/resources/youtube_channels.rst
index.rst

Add links and helpful youtube channels for students to explore content further. Addresses #10

Add resources

---

content/lectures/lecture_14.rst

Add slides and video for lecture 14

Lecture 14 Update

---

content/labs/arduino_stoplight.rst

After assignment feedback: add example video and clarify light order.

Clarify stoplight activity

---

content/resources/books.rst
content/resources/index.rst

Add list of useful books

---

content/lectures/lecture_15.rst
content/lectures/lecture_16.rst
content/lectures/lecture_17.rst
content/lectures/lecture_18.rst
content/lectures/lecture_19.rst
content/lectures/lecture_20.rst
content/lectures/lecture_21.rst
content/lectures/lecture_22.rst
content/lectures/lecture_23.rst
content/lectures/lecture_26.rst
content/lectures/lecture_27.rst
content/lectures/lecture_28.rst
content/lectures/lecture_29.rst
content/lectures/lecture_30.rst
content/lectures/lecture_31_32.rst

Add the lecture plans for the rest of the semester in their semi-final form.

Class plan update

---

content/labs/pressure_vessel_activity.rst
content/mechanical/bending_forces.rst

Fix minor typos and add some clarification where students were confused in the initial run through of the assignment.

Pressure vessel update

---

content/labs/index.rst
content/labs/strain_gage_activity.rst

Adds a basic activity to help students create an object instrumented with strain gages. Addresses #36

Strain gage activity

---

content/labs/index.rst
content/labs/project_presentations.rst

Add project presentation assignment

Project Presentations

---

content/lectures/lecture_21.rst
content/lectures/lecture_23.rst
content/lectures/lecture_24.rst
content/lectures/lecture_25.rst
content/lectures/lecture_26.rst

Add new lecture videos, slides, and notes.

Update lecture material
